package tui

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/lipgloss"
	"github.com/pchaganti/claude-session-manager/tui/internal/client"
)

// looksLikeCommand returns true if the string looks like a shell command
// rather than a meaningful session name.
func looksLikeCommand(s string) bool {
	for _, marker := range []string{"&&", "|", ";", "cd ", "./", "  "} {
		if strings.Contains(s, marker) {
			return true
		}
	}
	if strings.HasPrefix(s, "/") {
		return true
	}
	return false
}

// isAutoSlug returns true if the slug looks auto-generated by CC
// (pattern: word-word-word, three hyphen-separated lowercase words).
func isAutoSlug(slug string) bool {
	parts := strings.Split(slug, "-")
	if len(parts) != 3 {
		return false
	}
	for _, p := range parts {
		if len(p) == 0 {
			return false
		}
		for _, r := range p {
			if r < 'a' || r > 'z' {
				return false
			}
		}
	}
	return true
}

// pillName picks the best display name for a session:
// 1. User-set slug (via /rename) — not auto-generated
// 2. Ghostty tab title (if not a command)
// 3. Auto-generated slug
// 4. Project directory name
// 5. Session ID
func pillName(s client.Session) string {
	// User-set slug takes priority (e.g. "plugins-fun").
	if s.Slug != "" && !isAutoSlug(s.Slug) {
		return s.Slug
	}
	// Ghostty tab title if it's a real name.
	if s.GhosttyTab != "" && !looksLikeCommand(s.GhosttyTab) {
		return s.GhosttyTab
	}
	// Auto slug is still better than directory name.
	if s.Slug != "" {
		return s.Slug
	}
	if s.ProjectName != "" {
		return s.ProjectName
	}
	if len(s.SessionID) >= 8 {
		return s.SessionID[:8]
	}
	return s.SessionID
}

// renderPill renders a single session pill with state-colored background,
// icon, name, and optional pending-tool count badge.
func renderPill(s client.Session, selected bool, glowPos int) string {
	sc := stateColor(s.State)
	dimBg := stateColorDim(s.State)
	icon := stateIcon(s.State)

	name := pillName(s)

	label := icon + " " + name

	// Pending badge.
	if n := len(s.PendingTools); n > 0 {
		badgeStyle := lipgloss.NewStyle().
			Foreground(lipgloss.ANSIColor(15)).
			Background(colorBadgeBg).
			Bold(true).
			Padding(0, 1)
		label += " " + badgeStyle.Render(fmt.Sprintf("%d", n))
	}

	style := lipgloss.NewStyle().
		Padding(0, 1).
		Foreground(sc).
		Background(dimBg)

	if selected {
		accentColor := colorAccent
		if s.AutopilotMode == "yolo" {
			accentColor = colorOrange
		} else if s.AutopilotMode == "on" {
			accentColor = colorRunning
		}
		style = style.
			Bold(true).
			Foreground(lipgloss.ANSIColor(15)).
			Background(sc).
			Border(lipgloss.RoundedBorder()).
			BorderForeground(accentColor)
	}
	// Unselected pills: no border at all.

	return style.Render(label)
}
