package tui

import (
	"fmt"
	"strings"

	"github.com/charmbracelet/lipgloss"
	"github.com/pchaganti/claude-session-manager/tui/internal/client"
)

// looksLikeCommand returns true if the string looks like a shell command
// rather than a meaningful session name.
func looksLikeCommand(s string) bool {
	for _, marker := range []string{"&&", "|", ";", "cd ", "./", "  "} {
		if strings.Contains(s, marker) {
			return true
		}
	}
	if strings.HasPrefix(s, "/") {
		return true
	}
	return false
}

// isAutoSlug returns true if the slug looks auto-generated by CC
// (pattern: word-word-word, three hyphen-separated lowercase words).
func isAutoSlug(slug string) bool {
	parts := strings.Split(slug, "-")
	if len(parts) != 3 {
		return false
	}
	for _, p := range parts {
		if len(p) == 0 {
			return false
		}
		for _, r := range p {
			if r < 'a' || r > 'z' {
				return false
			}
		}
	}
	return true
}

// cleanTabName strips Ghostty prefixes like "✳ " (unsaved indicator).
func cleanTabName(name string) string {
	// Strip common prefixes: ✳, ●, etc.
	name = strings.TrimLeft(name, "✳●○◉◎ ")
	return strings.TrimSpace(name)
}

// pillName picks the best display name for a session:
// 1. User-set slug (via /rename) — not auto-generated
// 2. Ghostty tab title (if not a command)
// 3. Auto-generated slug
// 4. Project directory name
// 5. Session ID
func pillName(s client.Session) string {
	// User-set slug takes priority (e.g. "plugins-fun").
	if s.Slug != "" && !isAutoSlug(s.Slug) {
		return s.Slug
	}
	// Ghostty tab title if it's a real name.
	tab := cleanTabName(s.GhosttyTab)
	if tab != "" && !looksLikeCommand(tab) {
		return tab
	}
	// Project name (directory) before auto-generated slug.
	if s.ProjectName != "" && s.ProjectName != "/" {
		return s.ProjectName
	}
	// Auto slug as last resort before session ID.
	if s.Slug != "" {
		return s.Slug
	}
	if len(s.SessionID) >= 8 {
		return s.SessionID[:8]
	}
	return s.SessionID
}

// renderPill renders a single session pill with state-colored background,
// icon, name, and optional pending-tool count badge.
func renderPill(s client.Session, selected bool, glowPos int) string {
	return renderPillWithName(s, pillName(s), selected, glowPos)
}

// isPassiveState returns true if the session state is idle or dead (not actively working).
func isPassiveState(state string) bool {
	return state == "idle" || state == "dead"
}

// pillNameMaxLen returns the max name length based on state and selection.
// Selected pills show full 20-char names.
// Active unselected (running/waiting): 8 chars — visible but compact.
// Passive unselected (idle/dead): 4 chars — minimal footprint.
func pillNameMaxLen(state string, selected bool) int {
	if selected {
		return 20
	}
	if isPassiveState(state) {
		return 4
	}
	return 8 // running, waiting, or other active states
}

// renderPillWithName renders a pill using a pre-computed display name
// (which may include a disambiguator).
// Name length is tiered by state and selection for visual hierarchy.
func renderPillWithName(s client.Session, displayName string, selected bool, glowPos int) string {
	sc := stateColor(s.State)
	dimBg := stateColorDim(s.State)
	icon := stateIcon(s.State)

	compact := isPassiveState(s.State) && !selected
	maxLen := pillNameMaxLen(s.State, selected)

	var name string
	runes := []rune(displayName)
	if len(runes) > maxLen {
		name = string(runes[:maxLen])
	} else {
		name = displayName
	}

	label := icon + " " + name

	// Pending badge — rendered separately to avoid nested ANSI conflicts.
	badge := ""
	if n := len(s.PendingTools); n > 0 {
		badge = " " + lipgloss.NewStyle().
			Foreground(lipgloss.ANSIColor(15)).
			Background(colorBadgeBg).
			Bold(true).
			Padding(0, 1).
			Render(fmt.Sprintf("%d", n))
	}

	var style lipgloss.Style
	if compact {
		// Passive unselected pills: no background, just dim text — lighter visual weight.
		style = lipgloss.NewStyle().
			Padding(0, 0).
			Foreground(colorDimFg)
	} else {
		style = lipgloss.NewStyle().
			Padding(0, 1).
			Foreground(sc).
			Background(dimBg)
	}

	if selected {
		style = lipgloss.NewStyle().
			Padding(0, 1).
			Bold(true).
			Foreground(lipgloss.ANSIColor(15)).
			Background(sc).
			Underline(true)
	}

	return style.Render(label) + badge
}
